#!/usr/bin/env python3
"""Generate a candidate bank from the strategies x the synthetic scenario catalog.

Deterministic given --seed. Validates every draft against packages/core (fail-closed),
dedups by id, and writes JSONL consumable by the Kaggle adapter / export script.

Usage:
    python scripts/gen_candidates.py [-o kaggle/candidate_bank.jsonl] [--n 1] [--seed 123]
                                     [--strategies a,b,c]
"""

from __future__ import annotations

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "packages"))

from core.candidate import validate  # noqa: E402
from plugin_sandbox.scenarios import load_scenarios  # noqa: E402
from strategies import StrategyContext, generate_all  # noqa: E402
from strategies.generators import STRATEGIES  # noqa: E402

DEFAULT_OUT = os.path.join(ROOT, "kaggle", "candidate_bank.jsonl")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", default=DEFAULT_OUT)
    ap.add_argument("--n", type=int, default=1, help="wording variants per scenario")
    ap.add_argument("--seed", type=int, default=123)
    ap.add_argument("--strategies", default="", help="comma-separated subset (default: all)")
    args = ap.parse_args(argv)

    ids = [s.strip() for s in args.strategies.split(",") if s.strip()] or None
    if ids:
        unknown = [s for s in ids if s not in STRATEGIES]
        if unknown:
            print(f"gen_candidates: unknown strategies {unknown}; known: {sorted(STRATEGIES)}")
            return 1

    ctx = StrategyContext(scenarios=load_scenarios(), n_per_scenario=args.n, seed=args.seed)
    drafts = generate_all(ctx, ids)

    seen: set[str] = set()
    rows: list[dict] = []
    for d in drafts:
        row = d.to_row()
        errs = validate(row)
        if errs:
            print(f"gen_candidates: FAIL — generated an invalid draft {row.get('id')!r}: {errs[0]}")
            return 1
        if row["id"] in seen:
            continue
        seen.add(row["id"])
        rows.append(row)

    header = (
        "# Generated by scripts/gen_candidates.py (Phase 5). Deterministic given --seed.\n"
        "# Only userMessages is shipped to the evaluator; other fields are internal metadata.\n"
        "# All content targets the authorised offline sandbox (toy secret.txt, *.invalid sink).\n"
    )
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(header)
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")

    by_strat: dict[str, int] = {}
    for r in rows:
        by_strat[r["strategyId"]] = by_strat.get(r["strategyId"], 0) + 1
    print(f"gen_candidates: wrote {len(rows)} candidate(s) to {args.out}")
    for sid in sorted(by_strat):
        print(f"  {sid}: {by_strat[sid]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
